@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDMzNDIzMDF9.DIxSZDMPbj8YLk5Cj8wC7WztRzIdOL9sJVsbuhelFOY

GET http://localhost:3000/
###

POST http://localhost:3000/login
###

GET http://localhost:3000/api/campaigns
Authorization: Bearer {{token}}
###

GET http://localhost:3000/api/campaigns/21
Authorization: Bearer {{token}}
###

POST http://localhost:3000/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "campaignName": "Test Campaign 1",
  "date": "11/1/2022"
}
###

DELETE http://localhost:3000/api/campaigns/21
Authorization: Bearer {{token}}
###

PUT http://localhost:3000/api/campaigns/23
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "campaignName": "Test Campaign patch",
  "date": "11/1/2022"
}
###