@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDMwODIyMzJ9.QA_VlZjkiWwSI3Wcfwi-o8X1Z6Dh-wZmqrOjjec9Eik

GET http://localhost:3000/
###

POST http://localhost:3000/login
###

GET http://localhost:3000/api/campaigns
Authorization: Bearer {{token}}
###