@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDMwMTIwODJ9.KVa1p-SuDLo8ALPenn2fMIyRUeqUs-d3wos6yQthc1g

GET http://localhost:3000/
###

POST http://localhost:3000/login
###

GET http://localhost:3000/api/campaigns
Authorization: Bearer {{token}}
###